#Workflow
#Should Have name 
name: Hello

on:
  workflow_dispatch: 
#Jobs 
#should be inside the workflow 

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to everyone
        run: echo "Hello Dosto"
#Steps
#should be inside the job 

#Actions 
#should be inside the steps 
