#GoaL: whenever someone changes the python code the linter will check the syntax format and indenatin is 
# is currect or not 

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    #this step will automatically clone the code of the current branch into the runner 
    steps:
      - name: checkout/clone the code
        uses: actions/checkout@v7

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: install linter
        run: pip install ruff

      - name: check the files for linting 
        run: ruff check .

